### ISSUE TITLE
Liten feil

### ISSUE THREAD

**Issue by Bigrock76** [miui-scandinavia/MA-XML-7.0-NORWEGIAN#2]
Hei 

Når man skal kopiere tekst og skal velge. Så får man et valg som heter Avvelg alle. Der burde det stå velg alt siden det er det man gjør :) Eller veldig godt jobbet :)

**Comment by datagutt** [comment]
Takker, driver å oppdaterer oversettelsen nå. Den henger en måned etter snart :P
Regner med å ha det fikset til neste release (fredag).
