### ISSUE TITLE
HTML blir vist som tekst

### ISSUE THREAD

**Issue by ghost** [miui-scandinavia/MA-XML-7.0-NORWEGIAN#4]
![screenshot_2016-09-25-08-48-44-973_com android settings](https://cloud.githubusercontent.com/assets/13658843/18813519/26653e50-82fd-11e6-8cf8-0db41bf4b6cb.png)

**Comment by datagutt** [comment]
Hei,
Skal fikse dette i neste versjon.
Finner du flere feil, si i fra. Vet at oversettelsen henger litt etter for øyeblikket.
